version: 0.2

env:
  parameter-store:
    DOCKER_REGISTRY_USERNAME: /personalprojects/docker-credentials/username
    DOCKER_REGISTRY_PASSWORD: /personalprojects/docker-credentials/password
    # DOCKER_REGISTRY_URL: /personalprojects/docker-credentials/url
phases:
  install:
    runtime-versions:
      python: 3.11
  pre_build:
    commands:
      - echo "Installing Dependencies..."
      - pip install -r requirements.txt
      - docker login -u $DOCKER_REGISTRY_USERNAME -p $DOCKER_REGISTRY_PASSWORD
  build:
    commands:
      - echo "Building Started..."
      - docker build -t "docker.io/$DOCKER_REGISTRY_USERNAME/test-aws-pipeline:latest" .
  post_build:
    commands:
      - echo "Building completed successfully"
      - docker push "docker.io/$DOCKER_REGISTRY_USERNAME/test-aws-pipeline:latest"
